server:
  port: 8000

spring:
  application:
    name: DEMO
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: postgres
    password: jay@2019PT
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create